[workspace]
members = [
    "rust/day_1",
    "rust/day_2",
    "rust/day_3",
    "rust/day_4",
    "rust/day_5",
    "rust/day_6",
    "rust/day_7",
    "rust/day_8",
    "rust/day_9",
    "rust/day_10",
    "rust/day_11",
    "rust/day_12",
    "rust/day_13",
]